apps/market_web/lib/market_web/router.ex
defmodule MarketWeb.Router do
  use MarketWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MarketWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MarketWeb do
    pipe_through :browser

    live "/", MarketLive, :index
    # live "/:id", MarketLive, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", MarketWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MarketWeb.Telemetry
    end
  end
end

apps/market_web/lib/market_web/live/market_live.ex
defmodule MarketWeb.MarketLive do
  use MarketWeb, :live_view

  alias Market.Cashier
  alias Market.Customer
  alias Market.Line

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, market: nil, customers: %{}, lines: %{}, cashiers: %{})}
  end

  @impl true
  def handle_event("new_market", %{"multiplier" => multiplier}, socket) do
    multiplier =
      case Integer.parse(multiplier) do
        {x, _} -> x
        :error -> 1
      end

    market = Market.create(multiplier)
    Market.subscribe(market)

    {:noreply, assign(socket, market: market, customers: %{}, lines: %{}, cashiers: %{})}
  end

  def handle_event("new_customer", params, socket) do
    customers =
      for _ <- 1..customers(params), into: socket.assigns.customers do
        customer = Market.new_customer(socket.assigns.market, Enum.random(items(params)))
        {customer.pid, customer}
      end

    {:noreply, assign(socket, :customers, customers)}
  end

  def handle_event("new_line", _, socket) do
    line = Market.new_line(socket.assigns.market)
    lines = Map.put(socket.assigns.lines, line.pid, line)
    {:noreply, assign(socket, :lines, lines)}
  end

  def handle_event("new_cashier", %{"reductions" => reductions, "line" => line}, socket) do
    reductions =
      case Integer.parse(reductions) do
        {x, _} -> x
        :error -> 999
      end

    cashiers = create_cashier(line, socket.assigns.cashiers, reductions)
    {:noreply, assign(socket, :cashiers, cashiers)}
  end

  @impl true
  def handle_info({%Customer{} = customer, :updated}, socket) do
    customers = Map.put(socket.assigns.customers, customer.pid, customer)
    {:noreply, assign(socket, :customers, customers)}
  end

  def handle_info({%Line{} = line, :updated}, socket) do
    lines = Map.put(socket.assigns.lines, line.pid, line)
    {:noreply, assign(socket, :lines, lines)}
  end

  def handle_info({%Cashier{} = cashier, :updated}, socket) do
    cashiers = Map.put(socket.assigns.cashiers, cashier.pid, cashier)
    {:noreply, assign(socket, :cashiers, cashiers)}
  end

  defp customers(%{} = map), do: map |> Map.to_list() |> customers(1)
  defp customers([], acc), do: acc
  defp customers([{"shiftKey", true} | rest], acc), do: customers(rest, acc + 2)
  defp customers([{"altKey", true} | rest], acc), do: customers(rest, acc + 3)
  defp customers([{"ctrlKey", true} | rest], acc), do: customers(rest, acc + 5)
  defp customers([{"metaKey", true} | rest], acc), do: customers(rest, acc + 7)
  defp customers([_ | rest], acc), do: customers(rest, acc)

  defp items(%{"value" => "large"}), do: 20..39
  defp items(%{"value" => "medium"}), do: 10..19
  defp items(%{"value" => "small"}), do: 1..9

  defp create_cashier(line, cashiers, reductions) do
    line = '<#{line}>' |> :erlang.list_to_pid() |> Line.get()
    cashier = Line.new_cashier(line, reductions)
    Map.put(cashiers, cashier.pid, cashier)
  end
end

apps/market_web/lib/market_web/views/error_view.ex
defmodule MarketWeb.ErrorView do
  use MarketWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/market_web/lib/market_web/views/layout_view.ex
defmodule MarketWeb.LayoutView do
  use MarketWeb, :view
end

apps/market_web/lib/market_web/live/market_live.html.leex
<%= if @market do %>
  <section class="market">
    <h3><%= @market.pid %> - <%= @market.multiplier %>X</h3>

    <section class="shop">
      <h4>
        Shop 
        <button phx-disable-with="Creating..." phx-click="new_customer" value="small">Small Customer</button>
        <button phx-disable-with="Creating..." phx-click="new_customer" value="medium">Medium Customer</button>
        <button phx-disable-with="Creating..." phx-click="new_customer" value="large">Large Customer</button>
      </h4>

      <section class="customers">
        <%= @customers
            |> Stream.map(&elem(&1, 1))
            |> Enum.sort_by(&(&1.created_at))
            |> Stream.filter(&(&1.state in ~w(shopping done_shopping)))
            |> Enum.map(fn customer -> %>
          <div class="customer <%= customer.state %>">
            <b>CUSTOMER: <%= customer.pid %></b><br />
            CART: <%= customer.items_took %><br />
            BAG: <%= customer.items_processed %>
          </div>
        <% end) %>
      </section>
    </section>

    <section class="lines">
      <h4>
        Lines 
        <button phx-disable-with="Creating..." phx-click="new_line">New Line</button>
      </h4>

      <%= for {_, line} <- @lines do %>
        <div class="line">
          <div class="row">
            <div class="column">
              <b>LINE: <%= line.pid %></b>
            </div>
          </div>

          <form phx-submit="new_cashier" class="container">
            <div class="row">
              <input id="line" name="line" type="hidden" value="<%= line.pid %>">
              <input id="reductions" name="reductions" type="text" class="phx-blur-loading" placeholder="Reductions">
              <button phx-disable-with="Creating..." type="submit">New cashier</button>
            </div>
          </form>

          <div class="row">
            <div class="column">
              <div class="line-customers">
                <h5>Customers</h5>

                <%= for stale_customer <- line.customers, 
                    customer = @customers[stale_customer.pid] do %>
                  <div class="customer <%= customer.state %>">
                    <b>CUSTOMER: <%= customer.pid %></b><br />
                    CART: <%= customer.items_took %><br />
                    BAG: <%= customer.items_processed %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="column">
              <div class="cashiers">
                <h5>Cashiers</h5>

                <%= for stale_cashier <- line.cashiers,
                        cashier = @cashiers[stale_cashier.pid] do %>
                  <div class="cashier">
                    <b>CASHIER: <%= cashier.pid %></b><br />
                    REDUCTIONS: <%= cashier.reductions %></b><br />
                    
                    <%= if cashier.customer do %>
                      <% customer = @customers[cashier.customer.pid] %>
                      <div class="customer <%= customer.state %>">
                        <b>CUSTOMER: <%= customer.pid %></b><br />
                        CART: <%= customer.items_took %><br />
                        BAG: <%= customer.items_processed %>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </section>

    <section class="customers-done">
      <h4>Done</h4>
        
      <section class="customers">
        <%= @customers
            |> Stream.map(&elem(&1, 1))
            |> Enum.sort_by(&(&1.finished_at))
            |> Stream.filter(&(&1.state == "done"))
            |> Enum.map(fn customer -> %>
          <div class="customer <%= customer.state %>">
            <b>CUSTOMER: <%= customer.pid %></b><br />
            ITEMS: <%= customer.items_to_take %><br />
            TIME: <%= Float.round((customer.finished_at - customer.created_at) / 1000 * @market.multiplier, 2)  %> min<br />
            TIME/ITEM: <%= Float.round(((customer.finished_at - customer.created_at) / 1000 * @market.multiplier) / customer.items_to_take, 2) %> min/item
          </div>
        <% end) %>
      </section>
    </section>
  </section>
<% else %>
  <form phx-submit="new_market">
    <div class="row">
      <input id="multiplier" name="multiplier" type="text" class="phx-blur-loading" placeholder="Multiplier">
      <button phx-disable-with="Creating..." type="submit">New market</button>
    </div>
  </form>
<% end %>

apps/market_web/lib/market_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

apps/market_web/lib/market_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

apps/market_web/lib/market_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Market", suffix: " · Phoenix Framework" %>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
            <%# <li><%= link "New Market", to: Routes.market_path(@conn, :new) %1></li> %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>